# Generated by Django 5.2.4 on 2026-03-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='last_contacted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='next_step',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_version',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
